### ISSUE TITLE
Incorrect real world range estimate

### ISSUE THREAD

**Issue by Northcaptain** [evkx/evkx.github.io#1]
hello on the I4 edrive35 the real world range estimate are incorrect the 2kw heating is higher than non heating which is anormal.

**Comment by TheTechArch** [comment]
@Northcaptain thank you for this. I had added an incorrect miles to km conversion for the 120 scenario when I calculated new range.  This error affected ALL models. So thank you

https://evkx.net/models/bmw/i4/i4_edrive35/rangeandconsumption/
