### ISSUE TITLE
Incorrect data

### ISSUE THREAD

**Issue by jparsons2222** [evkx/evkx.github.io#10]
Incorrect data: "620km / 385mi"
https://github.com/evkx/evkx.github.io/blob/823ef155db4f0d5525371e0ca01e26c526a844e5/content/models/tesla/cybertruck/Cybertruck_AWD/rangeandconsumption.md?plain=1#L168

**Comment by TheTechArch** [comment]
Thank you for this feedback. I had a incorrect calculation earlier.  @jparsons2222
