### ISSUE TITLE
Gen1 Model 3 LR/Performance charging curve

### ISSUE THREAD

**Issue by ecarhengr** [evkx/evkx.github.io#11]
Gen 1 Model 3 LR and Performance have a better charge curve than current models, but on the site the curves are exactly the same.

Here is a video showing the difference: https://www.youtube.com/watch?v=Zx59coh_8I4&ab_channel=Bj%C3%B8rnNyland

For example the newer ones are below 100kW at 45-50%, but the old one continues above 100kW until 63%

**Comment by TheTechArch** [comment]
@ecarhengr thanks for this feedback. I have updated the curve on GEN1 LR and Performance from the latest test in spread sheet.
