### ISSUE TITLE
MG4 51 kWh Standard Range charging curve needs updating

### ISSUE THREAD

**Issue by yjchua** [evkx/evkx.github.io#17]
Currently, the [MG4 Standard 51 kWh's charging curve](https://evkx.net/models/mg/mg4/mg4_electric_standard/chargingcurve/) is identical to that of the 64 kWh version in evkx.net.

This is wrong.

The MG4 Standard 51 kWh only peaks at around 84-85 kW, not 135-140 kW.

[Bjørn Nyland has proven this in his MG4 51 kWh charging test video](https://www.youtube.com/watch?v=pFXfJe6Etnk).

**Comment by TheTechArch** [comment]
@yjchua this is updated. now. Thanks
